#!/command/with-contenv /usr/bin/bash

set -eo pipefail

exec 2>&1
exec /usr/bin/koyeb \
    --token "${KOYEB_TOKEN}" \
    --url "${KOYEB_URL:-https://app.koyeb.com}" \
    services logs \
    --type build \
    --since "$(date --date="-1 minutes" --rfc-3339=seconds)" \
    ${KOYEB_SERVICE}
