#!/command/with-contenv /usr/bin/bash

set -eo pipefail

if [ -z $KOYEB_SERVICE ]; then
    echo "KOYEB_SERVICE must be set"
    /run/s6/basedir/bin/halt
    exit 1
fi

if [ -z $KOYEB_TOKEN ]; then
    echo "KOYEB_TOKEN must be set"
    /run/s6/basedir/bin/halt
    exit 1
fi

for VAR in ${!SINK_JSON_@}
do
    CONFIG=$(echo "${VAR#SINK_JSON_}"| tr '[:upper:]' '[:lower:]').json
    eval "echo -e \$$VAR" >> "/etc/vector/${CONFIG}"
done

for VAR in ${!SINK_YAML_@}
do
    CONFIG=$(echo "${VAR#SINK_YAML_}"| tr '[:upper:]' '[:lower:]').yaml
    eval "echo -e \$$VAR" >> "/etc/vector/${CONFIG}"
done

for VAR in ${!SINK_TOML_@}
do
    CONFIG=$(echo "${VAR#SINK_TOML_}"| tr '[:upper:]' '[:lower:]').toml
    eval "echo -e \$$VAR" >> "/etc/vector/${CONFIG}"
done

for GIST in ${!GIST_@}
do
    NAME=$(echo "${GIST#GIST_}"| tr '[:upper:]' [':lower:'])
    TMP="/tmp/${NAME}"
    REMOTE=$(eval "echo \$$GIST")
    gh gist clone "${REMOTE}" "${TMP}"
    if [ $? -ne 0 ]
    then
        /run/s6/basedir/bin/halt
        exit $?
    fi
    mv "${TMP}"/* /etc/vector/
done

for RFILE in ${!REMOTE_FILE_@}
do
    NAME=$(echo "${RFILE#REMOTE_FILE_}"| tr '[:upper:]' [':lower:'])
    TMP="/tmp/${NAME}"
    mkdir "${TMP}"
    REMOTE=$(eval "echo \$$RFILE")
    curl --fail "${REMOTE}" --output "${TMP}"
    if [ $? -ne 0 ]
    then
        /run/s6/basedir/bin/halt
        exit $?
    fi
    mv "${TMP}"/* /etc/vector/
done

if [ "${DEBUG}" != "" ]
then
    mv /root/sink-console.toml /etc/vector/
fi

/usr/bin/vector --config-dir=/etc/vector validate
if [ $? -ne 0 ]
then
    /run/s6/basedir/bin/halt
    exit $?
fi
